services:
  repo-model:
    build:
      context: .
      dockerfile: Dockerfile.model
    container_name: repo-model
    expose:
      - "8233"
    ports:
      - "8233:8233"

  postgres:
    image: postgres:16
    container_name: repoguard-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8345:5432"

  repoguard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repoguard
    depends_on:
      - repo-model
    ports:
      - "8344:8000"

volumes:
  postgres_data:
