// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"
)

const createMetrics = `-- name: CreateMetrics :one
INSERT INTO metrics (
    installation,
    issues_closed,
    duplicate_issue_found,
    issues_colaborated_with
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, installation, issues_closed, duplicate_issue_found, issues_colaborated_with, created_at, updated_at
`

type CreateMetricsParams struct {
	Installation          string
	IssuesClosed          int64
	DuplicateIssueFound   int64
	IssuesColaboratedWith int64
}

func (q *Queries) CreateMetrics(ctx context.Context, arg CreateMetricsParams) (Metric, error) {
	row := q.db.QueryRow(ctx, createMetrics,
		arg.Installation,
		arg.IssuesClosed,
		arg.DuplicateIssueFound,
		arg.IssuesColaboratedWith,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.Installation,
		&i.IssuesClosed,
		&i.DuplicateIssueFound,
		&i.IssuesColaboratedWith,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMetricsByInstallation = `-- name: DeleteMetricsByInstallation :exec
DELETE FROM metrics
WHERE installation = $1
`

func (q *Queries) DeleteMetricsByInstallation(ctx context.Context, installation string) error {
	_, err := q.db.Exec(ctx, deleteMetricsByInstallation, installation)
	return err
}

const getMetricsByInstallation = `-- name: GetMetricsByInstallation :one
SELECT id, installation, issues_closed, duplicate_issue_found, issues_colaborated_with, created_at, updated_at
FROM metrics
WHERE installation = $1
`

func (q *Queries) GetMetricsByInstallation(ctx context.Context, installation string) (Metric, error) {
	row := q.db.QueryRow(ctx, getMetricsByInstallation, installation)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.Installation,
		&i.IssuesClosed,
		&i.DuplicateIssueFound,
		&i.IssuesColaboratedWith,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalMetrics = `-- name: GetTotalMetrics :one
SELECT
    COALESCE(SUM(issues_closed), 0)::BIGINT AS issues_closed,
    COALESCE(SUM(duplicate_issue_found), 0)::BIGINT AS duplicate_issue_found,
    COALESCE(SUM(issues_colaborated_with), 0)::BIGINT AS issues_colaborated_with
FROM metrics
`

type GetTotalMetricsRow struct {
	IssuesClosed          int64
	DuplicateIssueFound   int64
	IssuesColaboratedWith int64
}

func (q *Queries) GetTotalMetrics(ctx context.Context) (GetTotalMetricsRow, error) {
	row := q.db.QueryRow(ctx, getTotalMetrics)
	var i GetTotalMetricsRow
	err := row.Scan(&i.IssuesClosed, &i.DuplicateIssueFound, &i.IssuesColaboratedWith)
	return i, err
}

const incrementDuplicateIssuesFound = `-- name: IncrementDuplicateIssuesFound :one
UPDATE metrics
SET duplicate_issue_found = duplicate_issue_found + $2,
    updated_at = NOW()
WHERE installation = $1
RETURNING id, installation, issues_closed, duplicate_issue_found, issues_colaborated_with, created_at, updated_at
`

type IncrementDuplicateIssuesFoundParams struct {
	Installation        string
	DuplicateIssueFound int64
}

func (q *Queries) IncrementDuplicateIssuesFound(ctx context.Context, arg IncrementDuplicateIssuesFoundParams) (Metric, error) {
	row := q.db.QueryRow(ctx, incrementDuplicateIssuesFound, arg.Installation, arg.DuplicateIssueFound)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.Installation,
		&i.IssuesClosed,
		&i.DuplicateIssueFound,
		&i.IssuesColaboratedWith,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementIssuesClosed = `-- name: IncrementIssuesClosed :one
UPDATE metrics
SET issues_closed = issues_closed + $2,
    updated_at = NOW()
WHERE installation = $1
RETURNING id, installation, issues_closed, duplicate_issue_found, issues_colaborated_with, created_at, updated_at
`

type IncrementIssuesClosedParams struct {
	Installation string
	IssuesClosed int64
}

func (q *Queries) IncrementIssuesClosed(ctx context.Context, arg IncrementIssuesClosedParams) (Metric, error) {
	row := q.db.QueryRow(ctx, incrementIssuesClosed, arg.Installation, arg.IssuesClosed)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.Installation,
		&i.IssuesClosed,
		&i.DuplicateIssueFound,
		&i.IssuesColaboratedWith,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementIssuesCollaboratedWith = `-- name: IncrementIssuesCollaboratedWith :one
UPDATE metrics
SET issues_colaborated_with = issues_colaborated_with + $2,
    updated_at = NOW()
WHERE installation = $1
RETURNING id, installation, issues_closed, duplicate_issue_found, issues_colaborated_with, created_at, updated_at
`

type IncrementIssuesCollaboratedWithParams struct {
	Installation          string
	IssuesColaboratedWith int64
}

func (q *Queries) IncrementIssuesCollaboratedWith(ctx context.Context, arg IncrementIssuesCollaboratedWithParams) (Metric, error) {
	row := q.db.QueryRow(ctx, incrementIssuesCollaboratedWith, arg.Installation, arg.IssuesColaboratedWith)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.Installation,
		&i.IssuesClosed,
		&i.DuplicateIssueFound,
		&i.IssuesColaboratedWith,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMetrics = `-- name: ListMetrics :many
SELECT id, installation, issues_closed, duplicate_issue_found, issues_colaborated_with, created_at, updated_at
FROM metrics
ORDER BY created_at DESC
`

func (q *Queries) ListMetrics(ctx context.Context) ([]Metric, error) {
	rows, err := q.db.Query(ctx, listMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.Installation,
			&i.IssuesClosed,
			&i.DuplicateIssueFound,
			&i.IssuesColaboratedWith,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMetrics = `-- name: UpsertMetrics :one
INSERT INTO metrics (
    installation,
    issues_closed,
    duplicate_issue_found,
    issues_colaborated_with
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (installation)
DO UPDATE SET
    issues_closed = metrics.issues_closed + EXCLUDED.issues_closed,
    duplicate_issue_found = metrics.duplicate_issue_found + EXCLUDED.duplicate_issue_found,
    issues_colaborated_with = metrics.issues_colaborated_with + EXCLUDED.issues_colaborated_with,
    updated_at = NOW()
RETURNING id, installation, issues_closed, duplicate_issue_found, issues_colaborated_with, created_at, updated_at
`

type UpsertMetricsParams struct {
	Installation          string
	IssuesClosed          int64
	DuplicateIssueFound   int64
	IssuesColaboratedWith int64
}

func (q *Queries) UpsertMetrics(ctx context.Context, arg UpsertMetricsParams) (Metric, error) {
	row := q.db.QueryRow(ctx, upsertMetrics,
		arg.Installation,
		arg.IssuesClosed,
		arg.DuplicateIssueFound,
		arg.IssuesColaboratedWith,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.Installation,
		&i.IssuesClosed,
		&i.DuplicateIssueFound,
		&i.IssuesColaboratedWith,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
