// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Metric struct {
	ID                    uuid.UUID
	Installation          string
	IssuesClosed          int64
	DuplicateIssueFound   int64
	IssuesColaboratedWith int64
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}
