// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HomePage(authorizationURL string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-[#0F1322] text-white py-24\"><div class=\"container mx-auto px-4 text-center\"><h1 class=\"font-maven font-bold text-5xl md:text-7xl mb-6\"><span class=\"text-[#63DC76]\">GitHub</span> Repository's<br class=\"hidden md:inline\">Intelligent Gatekeeper</h1><p class=\"text-[#B026FF] font-maven text-xl md:text-2xl font-semibold mb-4\">Tired of sorting through duplicate issues?</p><p class=\"font-maven text-xl md:text-2xl font-semibold mb-12 max-w-3xl mx-auto\">Meet Repo Guard, the smart solution that keeps your GitHub repositories clean, organized, and efficient.</p><div class=\"flex flex-col sm:flex-row justify-center items-center gap-4\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL = templ.SafeURL(authorizationURL)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var3)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"inline-flex items-center justify-center gap-3 bg-[#90D3DF] hover:bg-[#7BBAC5] text-black font-rubik px-6 py-4 rounded-lg font-bold text-lg group transition-all duration-300 transform hover:scale-105 hover:shadow-lg\"><img src=\"../static/images/github_icon.svg\" alt=\"GitHub Icon\" class=\"w-6 h-6 transition-transform duration-300 group-hover:rotate-12\"> <span class=\"relative after:absolute after:bottom-0 after:left-0 after:w-full after:h-0.5 after:bg-black after:scale-x-0 after:origin-bottom-right after:transition-transform after:duration-300 group-hover:after:scale-x-100 group-hover:after:origin-bottom-left\">Install GitHub App</span></a> <a href=\"#learn-more\" class=\"inline-flex items-center justify-center gap-6 bg-transparent hover:bg-[#49E06C]/10 text-[#49E06C] hover:text-[#3AB057] font-rubik px-6 py-4 rounded-lg font-bold text-lg group transition-all duration-300 transform hover:scale-105 border-2 border-[#49E06C] hover:border-[#3AB057]\"><img src=\"../static/images/right_arrow.png\" alt=\"Right Arrow\" class=\"w-6 h-6 transition-transform duration-300 group-hover:translate-x-1\"> <span>Learn More</span></a></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Layout("Repo Guard").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
