// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SetupPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-[#0F1322] text-white min-h-screen py-24 font-maven\"><div class=\"container mx-auto px-4\"><div class=\"max-w-2xl mx-auto bg-white/10 rounded-2xl p-10 shadow-xl\"><h1 class=\"text-4xl md:text-5xl font-bold mb-4 text-center\">Setup <span class=\"text-[#63DC76]\">Repo Guard</span></h1><p class=\"text-center text-lg text-gray-300 mb-10\">Configure how Repo Guard should handle duplicate issues in your repositories.</p><form method=\"POST\" action=\"/setup/save\" class=\"space-y-10\"><!-- Toggle setting --><div class=\"flex items-center justify-between bg-white/5 rounded-xl p-6\"><div class=\"pr-6\"><label for=\"auto_close\" class=\"block text-xl font-semibold mb-2\">Automatically close duplicate issues</label><p class=\"text-gray-400 text-sm\">When enabled, Repo Guard will automatically close newly created issues that are detected as duplicates and link them to the original issue.</p></div><!-- Toggle --><label class=\"relative inline-flex items-center cursor-pointer\"><input type=\"checkbox\" id=\"auto_close\" name=\"auto_close\" class=\"sr-only peer\"><div class=\"w-14 h-8 bg-gray-600 rounded-full peer\n\t\t\t\t\t\t\t\t\tpeer-checked:bg-[#63DC76]\n\t\t\t\t\t\t\t\t\tafter:content-[''] after:absolute after:top-1 after:left-1\n\t\t\t\t\t\t\t\t\tafter:bg-[#0F1322] after:rounded-full after:h-6 after:w-6\n\t\t\t\t\t\t\t\t\tafter:transition-all peer-checked:after:translate-x-6\"></div></label></div><!-- Submit --><div class=\"flex justify-end\"><button type=\"submit\" class=\"inline-flex items-center justify-center gap-3\n\t\t\t\t\t\t\t\tbg-[#B026FF] hover:bg-[#9020DC]\n\t\t\t\t\t\t\t\ttext-white font-rubik px-8 py-4 rounded-lg font-bold text-lg\n\t\t\t\t\t\t\t\ttransition-all duration-300 transform hover:scale-105 hover:shadow-lg\">Save Configuration</button></div></form></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Setup configurations").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
